keys:
  - &qemu_maverick age1ns3f5tngge09jtdk42nkaxq7uqdqncfwvhse4e74uhqdwlqmyvns86uf03
  - &admin_paulov age15gwvllh0e2ngluc0q2csn23n86hefcqphf9h9yzrc4twq55fn52sum8nq7
creation_rules:
  - path_regex: secrets/maverick/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *qemu_maverick
      - *admin_paulov
