name: maverick-rebuild

on:
  push:
    branches: [master]
    paths:
      - systems/maverick/**
      - users/**
      - modules/**
      - flake.nix
      - flake.lock

jobs:
  rebuild:
    runs-on:
      group: builders
      labels: [self-hosted, maverick-builder]
    steps:
      - uses: actions/checkout@v6
      - run: nixos-rebuild switch --flake .
