test: ENC[AES256_GCM,data:tmDlM3iCX6ZfykCa4Q==,iv:ALeHpjBtY3RKHHrtKGKYjyhBNKbfyVCaA2u2VkmaxFs=,tag:4GlSGMs6IheN5ub/IMQg2w==,type:str]
#ENC[AES256_GCM,data:YV2NJU1zSXa+s8/6P/YUCA==,iv:NOGVFjs8VvDTYWN7AEH+FP7rrfY4ZKzSLA/Qex+v/VE=,tag:/daotyN5tXh73glHJtZOeA==,type:comment]
example_array:
    - ENC[AES256_GCM,data:Mq7oD8sSjV6R5k+GO/k=,iv:HM4PK+F5L4N/LCQt3jK6j79DOEUzbBhim3IZ10Hpys8=,tag:zb0ytrRI3c+1Ekc7zB1TCA==,type:str]
    - ENC[AES256_GCM,data:KelBaOHXpg+N6y3EPvA=,iv:FpuK3GcZ16l3tJtCOLLb6BJsQhBZw3XjM70r60iZyHw=,tag:AurcXuZE0wO9ifLMLJRZZQ==,type:str]
example_number: ENC[AES256_GCM,data:h1w2ECMv/Pimpw==,iv:RlxFCMiby+DrQCd/ntkN62zUchNkHSCRL9dwihPhmk8=,tag:m3Kjx+Ri1/gdvwTjKd5B+g==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:NleyOw==,iv:U4NsGY6I9Nv4rZsqhrNLlNJ1GP6ky4OWTOcWiYJNv34=,tag:npxTZTU2aXV36Jxih/tlSg==,type:bool]
    - ENC[AES256_GCM,data:Oq1xnbg=,iv:o6JbXEh8yAAGB84tBvQNMsBtK5JQ4nCv13scXhNlvT8=,tag:5W+LnqP8w0W5ql3nl1s22Q==,type:bool]
sops:
    lastmodified: "2026-03-18T00:21:02Z"
    mac: ENC[AES256_GCM,data:XaQXKb/hYRmOahl4NBM2+7kGs9Kpjh0DM7Wy36lAU379Oqv2BBxaqrAyA0ABhwxC80W00B1MXvkhOJlnY+eo2z2eCVL8HbQwElhLFQORYmbB2ffuzRZz93mRWd9LTerO4hgbDFJFgmn4vKj+AQRt18hrEcUmqUNUMkJfNa30IvE=,iv:p11fu2FVGMbDpnX8H0/ZmKYz9SdvojlWtHDe0rcE+4U=,tag:OfSOBGFo/BdFPidRXUWc5Q==,type:str]
    pgp:
        - created_at: "2026-03-18T00:20:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6H2ddj/s0T9AQ//Z1ZGT6SPziK+o352OboRHN9yrnw7WLXY6kgAnLpwRRAU
            uEI8uTYTjtaFPL7jPPeBsnMhUJkZir3sic3rip2DEuhqCpBBzRUK2+YmtqEwk77p
            yDy9+qoh5kCVOiOTtBRzOhYf8MlXXgazCj8F5onA1p/+JKTss7sBvvENa+pHM2sg
            66WRJiCwsO0UP1uKB/mCTc9tvg+ni+/xEGIrx+NmwSspNKVjAN7hyji03gFj9HlM
            /nR47zfL8+aipBa1edQsp3LBOo6WTno3JXiwZSUus0pEs4L7Cla3EP8OLdQFs6RP
            Mb+H79rhKuJJJdVs/GCBAmXOr+93DGZy2haLkge2Bxo7wJVaHSfBx/i5W9kCY0u0
            5E7UEqBR253s2wizAZRuL1zesTHGr2SRvoa0BX3ueSIkrIR6PK63TggV/WMzJbNv
            PfV1zYevjeWiAi4A4scdHGZ8MnX4jFXNd6m0CUDSFd/KTdeO5uWW507D0GmmHz0P
            hpxucQFNhe4wj2QBUQKWaVmiPPpN4BS9iFaGHoi102wz6BvNbGy4vEDlB6NDWc8b
            vhplHLm8BOd93FBNaG5cNlU42q9LAoBlAwf2ZPcAIfv5YckUnrl1US6QtJACfnYP
            fUAG2BWSqkdHWRXiHezrchduvBI8+D8vEJUtbXmPcghaQT/ECBYZRrqSDIkx/tPS
            WAECOksy1qSyQY8/0Iq1INM7WhfWO9uL88yS1wTZV5+ca2w4wSKW2lJGfMDTM699
            ryTpaikv3xJ9gQ8lKUQYwcBWRbAEQhsgr2EPXE4lnQmSrSUlmiEySXw=
            =kNTT
            -----END PGP MESSAGE-----
          fp: b82c4ca4c95f649438a96d9da1f675d8ffb344fd
    unencrypted_suffix: _unencrypted
    version: 3.12.1
