users:
    root:
        pass: ENC[AES256_GCM,data:d6O5el0ipjZfmisK1eL1pY/JkvQWWV7R/IN6Awo=,iv:LiceaBmoYIVDFxaM18ZcnuBpyXhXHG6/Xc/EIoGagwM=,tag:f3YQ6/ptgF0prFyhXvWy5w==,type:str]
    paulov:
        pass: ENC[AES256_GCM,data:xYIoLfar2EauuVUofPFS1y9MCAgi+Bjc,iv:ygpU6QNXIYVwsL42PeKHRkO+HMZicbXvAU3xeUuxoyw=,tag:9wMt8P6pvoyqtdOCgSu9dw==,type:str]
msmtp:
    users:
        default:
            pass: ENC[AES256_GCM,data:y80vdgboQndn5k7F9qIVMTUT/5yjo7dc,iv:IeJb8VlBy00cSJfV/oHJpilJhcW/+XRWQ9PsOy6ULyA=,tag:DqkvEQLhIskX67j/B5GP/A==,type:str]
grafana:
    secret_key: ENC[AES256_GCM,data:5rU9H9VKH8ADley6SQS8QKsjJHRkxFd8rRoD96LCqYwiSROO29rN0Q==,iv:zC+fQsKTkV3AjU2mTmByJI+igpUq/h3CwtbRvSywE8U=,tag:xhzoXnaRXrU+PDx+rtv9Ow==,type:str]
api:
    gemini:
        token: ENC[AES256_GCM,data:i68dDwr3kVe1nb+/JNXTXdCR3DS0a8aoKq1jWbyDADCHLUmNXRVq,iv:7gUxk4VT7Pb+XE/du0zlOqTI8alKJ9hqYHE5oxvf1WA=,tag:nCwiUkuD6X6ecq2JlKmLZg==,type:str]
    groq:
        token: ENC[AES256_GCM,data:FWYRE+i35YVmXzCBZx1sK1Y48fPeqBSAmuGk9lypokMF5P1FsMOg39Lk9mCo42u+9doLwS5eML8=,iv:O4OMoBh/9YaBZDfIdcCmutG3RVS04OH7Dj5rqIFMP8o=,tag:Ay2dAygRroc8adAFezA8Ew==,type:str]
sops:
    lastmodified: "2026-03-18T10:38:57Z"
    mac: ENC[AES256_GCM,data:6858LnVqA1dhcOJjnMAh/vJW64d6e9+pVSZ9jbjfJRas8/ebZIx6cz8+pFyCHsc6wOEknMPTWw0iCXl52rs//UO6TKYODIGarIFWpMIWwEv7H+ruNrgvXoXPr1ollA2yLR6uEDUn/EYrTh3vDK/pamuMDrjVX6J4xGbO1JnbEfk=,iv:1Hd+3DmcDfRq/+utBMnTr46JrQskdBVstwBWJBpOsxo=,tag:sR+0D3FiyLb+oSIeqMxgug==,type:str]
    pgp:
        - created_at: "2026-03-18T00:20:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6H2ddj/s0T9AQ//Z1ZGT6SPziK+o352OboRHN9yrnw7WLXY6kgAnLpwRRAU
            uEI8uTYTjtaFPL7jPPeBsnMhUJkZir3sic3rip2DEuhqCpBBzRUK2+YmtqEwk77p
            yDy9+qoh5kCVOiOTtBRzOhYf8MlXXgazCj8F5onA1p/+JKTss7sBvvENa+pHM2sg
            66WRJiCwsO0UP1uKB/mCTc9tvg+ni+/xEGIrx+NmwSspNKVjAN7hyji03gFj9HlM
            /nR47zfL8+aipBa1edQsp3LBOo6WTno3JXiwZSUus0pEs4L7Cla3EP8OLdQFs6RP
            Mb+H79rhKuJJJdVs/GCBAmXOr+93DGZy2haLkge2Bxo7wJVaHSfBx/i5W9kCY0u0
            5E7UEqBR253s2wizAZRuL1zesTHGr2SRvoa0BX3ueSIkrIR6PK63TggV/WMzJbNv
            PfV1zYevjeWiAi4A4scdHGZ8MnX4jFXNd6m0CUDSFd/KTdeO5uWW507D0GmmHz0P
            hpxucQFNhe4wj2QBUQKWaVmiPPpN4BS9iFaGHoi102wz6BvNbGy4vEDlB6NDWc8b
            vhplHLm8BOd93FBNaG5cNlU42q9LAoBlAwf2ZPcAIfv5YckUnrl1US6QtJACfnYP
            fUAG2BWSqkdHWRXiHezrchduvBI8+D8vEJUtbXmPcghaQT/ECBYZRrqSDIkx/tPS
            WAECOksy1qSyQY8/0Iq1INM7WhfWO9uL88yS1wTZV5+ca2w4wSKW2lJGfMDTM699
            ryTpaikv3xJ9gQ8lKUQYwcBWRbAEQhsgr2EPXE4lnQmSrSUlmiEySXw=
            =kNTT
            -----END PGP MESSAGE-----
          fp: b82c4ca4c95f649438a96d9da1f675d8ffb344fd
    unencrypted_suffix: _unencrypted
    version: 3.12.1
